# Generated by Django 4.0 on 2022-01-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_product', models.CharField(max_length=200)),
                ('picture_of_product', models.CharField(max_length=500)),
                ('nutriscore', models.CharField(max_length=20)),
                ('url_of_product', models.CharField(max_length=500)),
            ],
        ),
    ]
