# Generated by Django 4.0 on 2022-01-09 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nutriscore',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture_of_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url_of_product',
        ),
    ]
