# Generated by Django 4.0 on 2022-01-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_product_nutriscore_product_picture_of_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nutriscore_letter',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
