# Generated by Django 4.0 on 2022-03-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='energy_product',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fat_product',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='proteins_product',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sugar_product',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
